// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfEUcEy92RYi5tRp92n5kmx_yHZlP43e4',
    appId: '1:678727118050:web:b2c8eab2c0dc42f12ec2bb',
    messagingSenderId: '678727118050',
    projectId: 'studi-3e797',
    authDomain: 'studi-3e797.firebaseapp.com',
    storageBucket: 'studi-3e797.appspot.com',
    measurementId: 'G-15SHVD5QMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWchD3yuzEkcODIwkSZHVRCgeH76FMRq8',
    appId: '1:678727118050:android:0bb56a8cbf2d79ab2ec2bb',
    messagingSenderId: '678727118050',
    projectId: 'studi-3e797',
    storageBucket: 'studi-3e797.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyXoK9UCT-wEYXOBzNOaqozPwVK29jtKU',
    appId: '1:678727118050:ios:e2afab8e0b508a202ec2bb',
    messagingSenderId: '678727118050',
    projectId: 'studi-3e797',
    storageBucket: 'studi-3e797.appspot.com',
    iosClientId: '678727118050-unma8s0acr6u0oh5hdrj0jkehf45u2b7.apps.googleusercontent.com',
    iosBundleId: 'com.example.studiAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyXoK9UCT-wEYXOBzNOaqozPwVK29jtKU',
    appId: '1:678727118050:ios:8298acabc55467432ec2bb',
    messagingSenderId: '678727118050',
    projectId: 'studi-3e797',
    storageBucket: 'studi-3e797.appspot.com',
    iosClientId: '678727118050-2h90fbprvvkm0fjqevh67rbh7e8qf0ip.apps.googleusercontent.com',
    iosBundleId: 'com.example.studiAdmin.RunnerTests',
  );
}
