// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEWzV7mCCvLS9yHSP3i2TRNJL9F113SgM',
    appId: '1:85215898433:web:8725c5ea65b12dce130fc0',
    messagingSenderId: '85215898433',
    projectId: 'v-nex-groundup',
    authDomain: 'v-nex-groundup.firebaseapp.com',
    storageBucket: 'v-nex-groundup.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDahYcbAggmw3UN0vPu1H2KvC4otIpe5BY',
    appId: '1:85215898433:android:353f22f4333e9c8b130fc0',
    messagingSenderId: '85215898433',
    projectId: 'v-nex-groundup',
    storageBucket: 'v-nex-groundup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB92L_DAd6zRB2ZTzJS91wTANKHgIlPRQ',
    appId: '1:85215898433:ios:2398beb05bef2cc9130fc0',
    messagingSenderId: '85215898433',
    projectId: 'v-nex-groundup',
    storageBucket: 'v-nex-groundup.appspot.com',
    iosClientId: '85215898433-ic2vb743qmpko9847hstvb2jjmop0nev.apps.googleusercontent.com',
    iosBundleId: 'com.example.vNex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB92L_DAd6zRB2ZTzJS91wTANKHgIlPRQ',
    appId: '1:85215898433:ios:2398beb05bef2cc9130fc0',
    messagingSenderId: '85215898433',
    projectId: 'v-nex-groundup',
    storageBucket: 'v-nex-groundup.appspot.com',
    iosClientId: '85215898433-ic2vb743qmpko9847hstvb2jjmop0nev.apps.googleusercontent.com',
    iosBundleId: 'com.example.vNex',
  );
}
